### ISSUE TITLE
Package Installation Issue: @next/swc-darwin-arm64 Only Works on macOS arm64

### ISSUE THREAD

**Issue by itsTony4dev** [DeveLeb/Develeb-Platform#56]
I encountered an issue with the @next/sec-darwin-arm64 package that was recently added to our monorepo. This package is only compatible with macOS arm64, which causes problems for team members using other operating systems or architectures.

**Comment by the-refrigerator** [comment]
Is the issue still happening now? I tried recreating it on my machine and it worked fine.
